package ch6.ch6.exceptions.B_usingAtryStatement;

/*
 * Created by: Cristian Arroyo
 * on 20 April 2018 - 6:23 PM
 */

public class C_ThrowingASecondException {
}
